#! /usr/bin/env bash

echo "
# Generated by scripts/gen_filelist.sh

target_sources(prog PRIVATE"

# make paths relative to the project root, surround with quotes and add a tab for readability
find . -name "*.cpp" | sed -e "s/^.\\//\t\".\\/src\\//" -e "s/$/\"/"

echo -e ")\n"

