#! /usr/bin/env python3
import re
import sys
import make_uniform_setters

FIND_STRUCT: re.Pattern = re.compile(r"struct \S+ {.*?};", re.DOTALL)
# TODO: keep comments
COMMENTS: re.Pattern = re.compile(r"//.*$", re.MULTILINE)

def find_structs(file_contents: str) -> list[str]:
    file_contents = re.sub(COMMENTS, "", file_contents)
    return re.findall(FIND_STRUCT, file_contents)

def process_file(file_contents: str) -> str:
    structs: list[str] = find_structs(file_contents)
    output = ""
    for struct in structs:
        output += make_uniform_setters.transform_struct(struct)
    return output

SHADER_NAME: re.Pattern = re.compile(r"(.*?)(\.glsl)?$")

def shader_name(file_path: str) -> str:
    filename: str = file_path.split("/")[-1]
    name_match: re.Match | None = re.match(SHADER_NAME, filename)
    if name_match is not None:
        name: str = name_match.group(1)
    else:
        raise Exception(f"Invalid filename for shader {file_path}")
    name = name.replace(".", "_") # can't have dots in namespaces
    return name

def header(namespace: str) -> str:
    return (f"\n// this file autogenerated by {sys.argv[0]}\n"
             "#pragma once\n"
             "#include <glm/glm.hpp>\n"
             "#include <boost/hana.hpp>\n\n"
            f"namespace {namespace} {{\n"
             "typedef int sampler2D;\n"
           )

def footer() -> str:
    return "\n}\n\n"

if __name__ == "__main__":
    with open(sys.argv[1], 'r') as input_file:
        input_str: str = input_file.read()

    output: str = ""
    namespace: str = "Shader_" + shader_name(sys.argv[1])
    output += header(namespace)
    output += process_file(input_str)
    output += footer()

    with open(sys.argv[2], "w+") as output_file:
        output_file.write(output)

