
# Generated by scripts/gen_filelist.sh

target_sources(prog PRIVATE
	"./src/camera.cpp"
	"./src/genTerrain.cpp"
	"./src/imguiConfig.cpp"
	"./src/lighting.cpp"
	"./src/main.cpp"
	"./src/mesh.cpp"
	"./src/model.cpp"
	"./src/sceneObject.cpp"
	"./src/shaders.cpp"
	"./src/stbImageBuild.cpp"
	"./src/vertexData.cpp"
)

set(SHADER_FILES
	"./lightCube.frag.glsl"
	"./lightCube.vert.glsl"
	"./object.frag.glsl"
	"./object.vert.glsl"
	"./terrain.frag.glsl"
	"./terrain.vert.glsl"
)

