
# Generated by scripts/gen_filelist.sh

target_sources(prog PRIVATE
	"./src/camera.cpp"
	"./src/main.cpp"
	"./src/mesh.cpp"
	"./src/model.cpp"
	"./src/shaders.cpp"
	"./src/shaderStructs.cpp"
	"./src/stbImageBuild.cpp"
	"./src/vertexData.cpp"
)

